name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          profile: minimal
      
      - name: Build (default)
        run: cargo build --release --target wasm32-unknown-unknown
      
      - name: Build (ESP32)
        run: cargo build --release --target wasm32-unknown-unknown --features esp32
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm-build
          path: target/wasm32-unknown-unknown/release/igl_nano.wasm