name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      
      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-opt --version || echo "wasm-opt not installed, skipping optimization"
          if command -v wasm-opt >/dev/null 2>&1; then
            wasm-opt -Oz -o public/out.wasm target/wasm32-unknown-unknown/release/igl_nano.wasm
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: |
            target/wasm32-unknown-unknown/release/igl_nano.wasm
            public/out.wasm